variables:
  PROJECT_NAME: "FFXIV Utilities"
  MSBUILD_PATH: "Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\msbuild.exe"
before_script:
  - echo "starting build for %PROJECT_NAME%"
  - echo "Restoring NuGet Packages..."
  - nuget restore "%PROJECT_NAME%.sln"
stages:
  - build
  - test
build:
  tags:
  - c-sharp
  stage: build
  script:
  - echo "Release build..."
  - '"%programfiles(x86)%\%MSBUILD_PATH%" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "%PROJECT_NAME%.sln"'
  artifacts:
    untracked: true